---
section: config
title: 執行組態和管理工作
entries:
- title: 配置 Active IQ Unified Manager
  url: "/config/concept_configure_unified_manager.html"
  entries:
  - title: 組態順序總覽
    url: "/config/concept_overview_of_configuration_sequence.html"
  - title: 存取 Unified Manager Web UI
    url: "/config/task_access_unified_manager_web_ui.html"
  - title: 執行 Unified Manager Web UI 的初始設置
    url: "/config/task_perform_initial_setup_of_unified_manager_web_ui.html"
  - title: 新增叢集
    url: "/config/task_add_clusters.html"
  - title: 配置 Unified Manager 以發送警報通知
    url: "/config/task_configure_unified_manager_to_send_alert_notifications.html"
    entries:
    - title: 設定事件通知設定
      url: "/config/task_configure_event_notification_settings.html"
    - title: 啟用遠端驗證
      url: "/config/task_enable_remote_authentication.html"
    - title: 禁用遠端身份驗證的嵌套群組
      url: "/config/task_disable_nested_groups_from_remote_authentication.html"
    - title: 設定身份驗證服務
      url: "/config/task_set_up_authentication_services.html"
    - title: 新增驗證伺服器
      url: "/config/task_add_authentication_servers.html"
    - title: 測試身份驗證伺服器的配置
      url: "/config/task_test_configuration_of_authentication_servers_um_6_0.html"
    - title: 新增警示
      url: "/config/task_add_alerts.html"
  - title: 更改本機用戶密碼
    url: "/config/task_change_local_user_password.html"
  - title: 設定工作階段閒置逾時
    url: "/config/task_set_session_inactivity_timeout.html"
  - title: 透過 CLI 設定工作階段逾時
    url: "/config/task_set_session_timeout_CLI.html"
  - title: 更改 Unified Manager 主機名
    url: "/config/concept_change_unified_manager_host_name.html"
    entries:
    - title: 更改 Unified Manager 虛擬設備主機名
      url: "/config/task_change_unified_manager_host_name_on_vmware.html"
      entries:
      - title: 產生HTTPS安全性憑證
        url: "/config/task_generate_an_https_security_certificate_ocf.html"
      - title: 重新啟動Unified Manager虛擬機器
        url: "/config/task_restart_unified_manager_virtual_machine.html"
    - title: 在 Linux 系統上變更 Unified Manager 主機名
      url: "/config/task_change_um_host_name_on_rhel.html"
  - title: 啟用和停用基於策略的儲存管理
    url: "/config/task_enable_and_disable_policy_based_storage_management.html"
- title: 設定 Unified Manager 備份
  url: "/config/concept_configure_um_backup.html"
- title: 管理功能設定
  url: "/config/concept_manage_feature_settings.html"
  entries:
  - title: 啟用原則型儲存管理
    url: "/config/concept_policy_based_storage_management.html"
  - title: 啟用 API 網關
    url: "/config/concept_api_gateway.html"
  - title: 指定不活動逾時
    url: "/config/concept_inactivity_timeout.html"
  - title: 啟用 Active IQ 入口網站事件
    url: "/config/concept_active_iq_platform_events.html"
  - title: 啟用和停用合規性安全性設置
    url: "/config/concept_security_dashboard.html"
  - title: 啟用和停用腳本上傳
    url: "/config/task_enable_and_disable_ability_to_upload_scripts.html"
  - title: 新增登入橫幅
    url: "/config/concept_login_banner.html"
- title: 使用維護控制台
  url: "/config/task_use_maintenance_console.html"
  entries:
  - title: 維護主控台提供哪些功能
    url: "/config/concept_what_functionality_maintenance_console_provides.html"
  - title: 維護使用者的功能
    url: "/config/concept_what_maintenance_user_does.html"
  - title: 診斷使用者功能
    url: "/config/concept_what_diagnostic_user_does.html"
  - title: 存取維護主控台
    url: "/config/task_access_maintenance_console.html"
  - title: 使用 vSphere VM 控制台存取維護控制台
    url: "/config/task_access_maintenance_console_using_vsphere.html"
  - title: 維護主控台功能表
    url: "/config/concept_maintenance_console_menu.html"
    entries:
    - title: 網路組態功能表
      url: "/config/reference_network_configuration_menu.html"
    - title: 系統組態功能表
      url: "/config/reference_system_configuration_menu.html"
    - title: 支援與診斷功能表
      url: "/config/reference_support_and_diagnostics_menu.html"
    - title: 其他功能表選項
      url: "/config/reference_additional_menu_options.html"
  - title: 在 Windows 上變更維護使用者密碼
    url: "/config/task_change_maintenance_user_password_on_windows.html"
  - title: 在 Linux 系統上變更 umadmin 密碼
    url: "/config/task_change_umadmin_password_on_rhel.html"
  - title: 更改 Unified Manager 用於 HTTP 和 HTTPS 協定的端口
    url: "/config/task_change_ports_um_uses_for_http_and_https_protocols.html"
  - title: 新增網路介面
    url: "/config/task_add_additional_network_interfaces.html"
  - title: 重新產生客戶端憑證
    url: "/config/task_regenerate_client_certificate.html"
  - title: 向 Unified Manager 資料庫目錄新增磁碟空間
    url: "/config/concept_add_disk_space_to_um_database_directory.html"
    entries:
    - title: 為Linux主機的資料目錄新增空間
      url: "/config/task_add_space_to_data_directory_of_um_linux_host.html"
    - title: 為VMware虛擬機器資料盤新增空間
      url: "/config/task_add_space_to_data_disk_of_vmware_virtual_machine.html"
    - title: 為 Microsoft Windows 伺服器的邏輯磁碟機新增空間
      url: "/config/task_add_space_to_data_disk_of_windows_server.html"
- title: 管理使用者存取權
  url: "/config/concept_manage_user_access.html"
  entries:
  - title: 新增使用者
    url: "/config/task_add_users.html"
    entries:
    - title: 建立資料庫用戶
      url: "/config/task_create_database_user.html"
  - title: 編輯用戶設定
    url: "/config/task_edit_user_setts.html"
  - title: 查看用戶
    url: "/config/task_view_users.html"
  - title: 刪除使用者或群組
    url: "/config/task_delete_users_or_groups.html"
  - title: 什麼是RBAC
    url: "/config/concept_what_rbac_is.html"
  - title: 以角色為基礎的存取控制功能
    url: "/config/concept_what_role_based_access_control_does.html"
  - title: 使用者類型定義
    url: "/config/reference_definitions_of_user_types.html"
  - title: 使用者角色定義
    url: "/config/reference_definitions_of_user_roles.html"
  - title: Unified Manager使用者角色與功能
    url: "/config/reference_unified_manager_roles_and_capabilities.html"
- title: 管理 SAML 身份驗證設定
  url: "/config/concept_manage_saml_authentication_settings_um.html"
  entries:
  - title: 身分識別供應商要求
    url: "/config/reference_identity_provider_requirements_um.html"
  - title: 啟用SAML驗證
    url: "/config/task_enable_saml_authentication_um.html"
  - title: 更改用於 SAML 身份驗證的身份提供者
    url: "/config/task_change_identity_provider_idp_used_for_saml_authentication.html"
  - title: Unified Manager 安全性憑證變更後更新 SAML 驗證設定
    url: "/config/task_update_saml_authentication_after_um_certificate_change.html"
  - title: 停用SAML驗證
    url: "/config/task_disable_saml_authentication_um.html"
  - title: 從維護控制台停用 SAML 驗證
    url: "/config/task_disable_saml_authentication_from_maintenance_console_um.html"
  - title: SAML驗證頁面
    url: "/config/reference_saml_authentication_page_um.html"
- title: 管理身份驗證
  url: "/config/concept_manage_authentication.html"
  entries:
  - title: 編輯身份驗證伺服器
    url: "/config/task_edit_authentication_servers.html"
  - title: 刪除身份驗證伺服器
    url: "/config/task_delete_authentication_servers.html"
  - title: 使用Active Directory或OpenLDAP驗證
    url: "/config/concept_authentication_with_active_directory_or_openldap.html"
  - title: 稽核記錄
    url: "/config/concept_audit_logging.html"
    entries:
    - title: 配置審計日誌
      url: "/config/task_configure_audit_logs.html"
    - title: 啟用稽核日誌的遠端記錄
      url: "/config/task_enable_remote_logging_of_audit_logs.html"
  - title: 遠端驗證頁面
    url: "/config/reference_remote_authentication_page.html"
- title: 管理安全性憑證
  url: "/config/concept_manage_security_certificates_ocf.html"
  entries:
  - title: 查看HTTPS安全證書
    url: "/config/task_view_https_security_certificate_ocf.html"
  - title: 下載 HTTPS 憑證簽署請求
    url: "/config/task_download_an_https_certificate_sign_request_ocf.html"
  - title: 安裝 CA 簽署並傳回的 HTTPS 憑證
    url: "/config/task_install_ca_signed_and_returned_https_certificate.html"
  - title: 安裝使用外部工具產生的 HTTPS 憑證
    url: "/config/concept_install_https_certificate_generated_using_external_tools.html"
  - title: 憑證管理的頁面說明
    url: "/config/concept_page_descriptions_for_certificate_management.html"
    entries:
    - title: HTTPS憑證頁面
      url: "/config/reference_https_dialog_box_ocf.html"
    - title: 重新產生HTTPS憑證對話方塊
      url: "/config/reference_regenerate_https_certificate_dialog_box.html"
